### ISSUE TITLE
when i type start give following error

### ISSUE THREAD

**Issue by djwalkzz16** [Duerocraft/AternosAPI#5]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    cmd(icmd)
  File "main.py", line 9, in cmd
    print(server.StartServer())
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aternosapi/__init__.py", line 34, in StartServer
    serverstatus = self.GetStatus()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aternosapi/__init__.py", line 29, in GetStatus
    status = webdata.find('span', class_='statuslabel-label').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'``

**Comment by nsde** [comment]
I get the same error!

**Comment by Matias-source** [comment]
I fixed it using cloudscraper instead of requests.

https://github.com/Matias-source/AternosAPI

**Comment by nsde** [comment]
LMAO, Thankss!!
