### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by nsde** [Duerocraft/AternosAPI#9]
```
Traceback (most recent call last):
  File "C:\Users\xitzf\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:/Users/xitzf/Documents/NSDE/neovision/src/bot.py", line 397, in aternos
    await ctx.send(server.StartServer())
  File "C:\Users\xitzf\AppData\Local\Programs\Python\Python38\lib\site-packages\aternosapi\__init__.py", line 34, in StartServer  
    serverstatus = self.GetStatus()
  File "C:\Users\xitzf\AppData\Local\Programs\Python\Python38\lib\site-packages\aternosapi\__init__.py", line 29, in GetStatus
    status = webdata.find('span', class_='statuslabel-label').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xitzf\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\xitzf\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\xitzf\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'get_text'

```

**Comment by DuckDictatorship** [comment]
Hi! I don't know if you still have this problem but I noticed that for me at least, this only occured when I ran my code in repl.it. It worked fine when I ran it as a .py file through the command line.

**Comment by ep1cst** [comment]
> 
> 
> Hi! I don't know if you still have this problem but I noticed that for me at least, this only occured when I ran my code in repl.it. It worked fine when I ran it as a .py file through the command line.

I tried doing this but it gave me the exact same error in command prompt and python IDLE. Any help?

**Comment by DuckDictatorship** [comment]
> I tried doing this but it gave me the exact same error in command prompt and python IDLE. Any help?



To clarify, I found that it only works when in the weird cmd prompt you can find in the examples folder here on the git. 
(I'm a newbie for python so no clue why that happens)

`
def cmd(cmd):
	if cmd == "start":
		print(server.StartServer())
	if cmd == "stop":
		print(server.StopServer())
	if cmd == "status":
		print(server.GetStatus())
	if cmd == "info":
		print(server.GetServerInfo())

while True:
	icmd = input("[*] > ")
	cmd(icmd)
`

that is the code that changes the console and makes it work. Weirdly, that's the only way I found.

**Comment by DuckDictatorship** [comment]
@ep1cst 

Also I found that for me, repl.it doesn't work but in console you can run `print(server.StopServer())` which works for some reason.

**Comment by zro404** [comment]
### The API simply doesn't work as Cloudflare (where Aternos is hosted on) BLOCKS requests from repl.it

**Comment by nsde** [comment]
> ### The API simply doesn't work as Cloudflare (where Aternos is hosted on) BLOCKS requests from repl.it

But I also have problems *without* repl.it...

**Comment by ProgrammAbel** [comment]
I also have this issue, and I'm not using repl.it... I have the exact same example that is in the github repo. I think in general the instructions to get this running are a little vague - I would be happy to contribute but I need to know how to do it first!

**Comment by nsde** [comment]
> I would be happy to contribute but I need to know how to do it first!
You can do a fork/pull request and edit the code :)

**Comment by Matias-source** [comment]
I fixed it using cloudscraper instead of requests.

https://github.com/Matias-source/AternosAPI

**Comment by nsde** [comment]
👍

**Comment by ep1cst** [comment]
> 
> 
> I fixed it using cloudscraper instead of requests.
> 
> https://github.com/Matias-source/AternosAPI

Still doesn't work?

**Comment by Matias-source** [comment]
> > I fixed it using cloudscraper instead of requests.
> > https://github.com/Matias-source/AternosAPI
> 
> Still doesn't work?

It works, if you have any problem, let me know.

**Comment by ep1cst** [comment]
> 
> 
> > > I fixed it using cloudscraper instead of requests.
> > > https://github.com/Matias-source/AternosAPI
> > 
> > 
> > Still doesn't work?
> 
> It works, if you have any problem, let me know.

I wouldn't be saying it doesn't work if it worked. I've followed your API source, done the exact same code and it gives me the exact same error as the title and more errors because of the `get_text` function.

**Comment by nsde** [comment]
:(

**Comment by Gargantuan5k** [comment]
> 
> 
> I fixed it using cloudscraper instead of requests.
> 
> https://github.com/Matias-source/AternosAPI

I tried using this and it worked, but I tried again the next day andd it started giving the same error again ...

File "/AternosAPI/aternosapi/__init__.py", line 30, in GetStatus
    status = webdata.find('span', class_='statuslabel-label').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by DuckDictatorship** [comment]
> I fixed it using cloudscraper instead of requests.
> 
> https://github.com/Matias-source/AternosAPI

This addition is great, but sadly cloudflare updated and it sends back 
`cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.`

There is not a paid version...

**Comment by nsde** [comment]
:(

**Comment by ChromeUniverse** [comment]
> > I fixed it using cloudscraper instead of requests.
> > https://github.com/Matias-source/AternosAPI
> 
> This addition is great, but sadly cloudflare updated and it sends back
> `cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.`
> 
> There is not a paid version...

Dead thread, but I decided to post this anyways :-P

There totally is a paid version for Cloudscaper, but you need to speak directly with **VeNoMouSNZ#5979** through Discord. They're the person maintaining the Cloudscraper project, and I actually got in touch with them to get some more information, but honestly, it's all really sketchy. They didn't even bother to set up a website or add a link with more info on the project's README.

I would share more information here but I ended up deleting my DMs with them. 🤦 Sorry about that. Hope this helps, though.

**Comment by DuckDictatorship** [comment]
> > > I fixed it using cloudscraper instead of requests.
> > > https://github.com/Matias-source/AternosAPI
> > 
> > 
> > This addition is great, but sadly cloudflare updated and it sends back
> > `cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.`
> > There is not a paid version...
> 
> Dead thread, but I decided to post this anyways :-P
> 
> There totally is a paid version for Cloudscaper, but you need to speak directly with **VeNoMouSNZ#5979** through Discord. They're the person maintaining the Cloudscraper project, and I actually got in touch with them to get some more information, but honestly, it's all really sketchy. They didn't even bother to set up a website or add a link with more info on the project's README.
> 
> I would share more information here but I ended up deleting my DMs with them. 🤦 Sorry about that. Hope this helps, though.

I couldn't even find a single thing relating to a paid version anywhere other than this thread lol. That guy is totally scamming, I doubt the paid version even has a single character changed from the free one. With no website, no way he makes enough money off that to justify locking stuff behind paywalls
